name: Update Flex endpoint

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  call-flex-update:
    uses: ./.github/workflows/callable-flex-update.yml
    with:
      contrib: false
      branch: master
